// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		| prismic.AnyRegularField
		| prismic.GroupField
		| prismic.NestedGroupField
		| prismic.SliceZone
	>,
	TLang extends string,
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			| prismic.CustomTypeModelFetchGroupLevel1
			| prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
			infer TGroupData
		>
			? prismic.GroupField<
					PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
				>
			: never
	} & // Other fields
	{
		[TFieldKey in Extract<
			TRelationship['fields'][number],
			string
		>]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
	}

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string,
> = {
	[ID in Exclude<
		TCustomType[number],
		string
	>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>
}[Exclude<TCustomType[number], string>['id']]

/**
 * Item in *Product → Tags*
 */
export interface ProductDocumentDataTagsItem {
	/**
	 * Product tag field in *Product → Tags*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.tags[].product_tag
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	product_tag: ContentRelationshipFieldWithData<
		[
			{
				id: 'product_tag'
				fields: [
					'name',
					{
						id: 'light_theme'
						fields: ['content', 'border', 'background']
					},
					{
						id: 'dark_theme'
						fields: ['content', 'border', 'background']
					},
				]
			},
		]
	>
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
	/**
	 * Name field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField

	/**
	 * Tags field in *Product*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.tags[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<ProductDocumentDataTagsItem>>

	/**
	 * Brand field in *Product*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.brand
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	brand: prismic.KeyTextField

	/**
	 * Price field in *Product*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	price: prismic.NumberField

	/**
	 * Image field in *Product*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<'Extended' | 'Mobile'>

	/**
	 * Link field in *Product*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product.link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

	/**
	 * Extended field in *Product*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: product.extended
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	extended: prismic.BooleanField
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<ProductDocumentData>,
		'product',
		Lang
	>

/**
 * Item in *Product tag → Light theme*
 */
export interface ProductTagDocumentDataLightThemeItem {
	/**
	 * content field in *Product tag → Light theme*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.light_theme[].content
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	content: prismic.ColorField

	/**
	 * Border field in *Product tag → Light theme*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.light_theme[].border
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	border: prismic.ColorField

	/**
	 * Background field in *Product tag → Light theme*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.light_theme[].background
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background: prismic.ColorField
}

/**
 * Item in *Product tag → Dark theme*
 */
export interface ProductTagDocumentDataDarkThemeItem {
	/**
	 * Content field in *Product tag → Dark theme*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.dark_theme[].content
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	content: prismic.ColorField

	/**
	 * Border field in *Product tag → Dark theme*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.dark_theme[].border
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	border: prismic.ColorField

	/**
	 * Background field in *Product tag → Dark theme*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.dark_theme[].background
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background: prismic.ColorField
}

/**
 * Content for Product tag documents
 */
interface ProductTagDocumentData {
	/**
	 * Name field in *Product tag*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField

	/**
	 * Light theme field in *Product tag*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.light_theme[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	light_theme: prismic.GroupField<
		Simplify<ProductTagDocumentDataLightThemeItem>
	>

	/**
	 * Dark theme field in *Product tag*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: product_tag.dark_theme[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	dark_theme: prismic.GroupField<
		Simplify<ProductTagDocumentDataDarkThemeItem>
	>
}

/**
 * Product tag document from Prismic
 *
 * - **API ID**: `product_tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductTagDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<ProductTagDocumentData>,
		'product_tag',
		Lang
	>

/**
 * Item in *settings → Socials*
 */
export interface SettingsDocumentDataSocialsItem {
	/**
	 * Label field in *settings → Socials*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField

	/**
	 * External url field in *settings → Socials*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[].external_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	external_url: prismic.KeyTextField

	/**
	 * Icon field in *settings → Socials*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	icon: prismic.SelectField<
		| 'instagram'
		| 'facebook'
		| 'x'
		| 'tiktok'
		| 'vimeo'
		| 'behance'
		| 'youtube'
		| 'linkedin'
	>
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
	/**
	 * Site name field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mon site
	 * - **API ID Path**: settings.site_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	site_name: prismic.KeyTextField

	/**
	 * Email field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.email
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField

	/**
	 * Socials field in *settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<SettingsDocumentData>,
		'settings',
		Lang
	>

/**
 * Content for Terms documents
 */
interface TermsDocumentData {
	/**
	 * Section title field in *Terms*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: terms.section_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	section_title: prismic.KeyTextField

	/**
	 * Button label field in *Terms*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: terms.button_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	button_label: prismic.KeyTextField

	/**
	 * Content field in *Terms*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: terms.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField
}

/**
 * Terms document from Prismic
 *
 * - **API ID**: `terms`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TermsDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<TermsDocumentData>,
		'terms',
		Lang
	>

export type AllDocumentTypes =
	| ProductDocument
	| ProductTagDocument
	| SettingsDocument
	| TermsDocument

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>
	}

	namespace Content {
		export type {
			ProductDocument,
			ProductDocumentData,
			ProductDocumentDataTagsItem,
			ProductTagDocument,
			ProductTagDocumentData,
			ProductTagDocumentDataLightThemeItem,
			ProductTagDocumentDataDarkThemeItem,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataSocialsItem,
			TermsDocument,
			TermsDocumentData,
			AllDocumentTypes,
		}
	}
}
